version: '3'

volumes:
  postgres_data_vol:
    external: false

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_USER: etherpaduser
      POSTGRES_PASSWORD: etherpadpass
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data/
    restart: always

  etherpad:
    image: etherpad/etherpad:develop
    environment:
      DB_HOST: postgresql
      DB_NAME: etherpad
      DB_PASS: etherpadpass
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: etherpaduser
      LOGLEVEL: "debug"
    depends_on:
      - postgresql
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 9002:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - etherpad
    restart: always
